### ISSUE TITLE
Why'd ya private your repositories?

### ISSUE THREAD

**Issue by afkvido** [vini2003/Hammer#2]

**Comment by afkvido** [comment]
Like this: https://github.com/vini2003/Black-Hole

**Comment by afkvido** [comment]
Why u private ur repos?

**Comment by vini2003** [comment]
I felt like it.

**Comment by afkvido** [comment]
I've heard that before. There **is** a reason behind that, if you're not going to share it then don't share it.

**Comment by afkvido** [comment]
"I felt like it" is what Apple says when they don't prefix their product with "i" because someone already registered that prodcut already.

**Comment by vini2003** [comment]
Are you OK?

**Comment by afkvido** [comment]
Please don't try to purge the mods anyways, I have copies of the blackhole mod for example.

**Comment by vini2003** [comment]
I... don't care?

**Comment by afkvido** [comment]
> I... don't care?

Then, **why** are you privating the repos?

**Comment by vini2003** [comment]
I'm sure you've misunderstood me, so I'll be more direct - I don't care what you think, and this is not the place to talk about it.

**Comment by afkvido** [comment]
Thank you for being more direct, I didn't understand what you meant.

**Comment by afkvido** [comment]
Anyways ur a clown bye child

**Comment by vini2003** [comment]
Have fun in kindergarten! :)

**Comment by afkvido** [comment]
> Have fun in kindergarten! :)

Alr I will :)

**Comment by Devan-Kerman** [comment]
massive copium

**Comment by afkvido** [comment]
fr ;v

**Comment by Devan-Kerman** [comment]
I was talking about you

**Comment by vini2003** [comment]
> fr ;v

That is not the flex you think it is.

**Comment by afkvido** [comment]
Thats ok

**Comment by rocketfromdiscord093** [comment]
vini2003 is a clown

**Comment by rocketfromdiscord093** [comment]
bro needs to go back to preshcool he dont even know math 💀
